apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
    - /etc/alertmanager/*.rules

    scrape_configs:
    - job_name: kubelets
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node

    - job_name: standard-endpoints
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_name]
        regex: prometheus|kubernetes|node-exporter|kube-state-metrics|etcd-k8s
      - action: replace
        source_labels: [__meta_kubernetes_service_name]
        target_label: job
      - action: replace
        source_labels: [__meta_kubernetes_service_name]
        regex: kubernetes
        target_label: __scheme__
        replacement: https

    - job_name: kube-components
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - action: replace
        source_labels: [__meta_kubernetes_service_name]
        target_label: job
        regex: "kube-(.*)-prometheus-discovery"
        replacement: "kube-${1}"
      - action: keep
        source_labels: [__meta_kubernetes_service_name]
        regex: "kube-(.*)-prometheus-discovery"
      - action: keep
        source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: "prometheus"

    - job_name: ec2

      ec2_sd_configs:
      - region: us-east-1
        access_key: aws_access_key
        secret_key: aws_secret_key
        refresh_interval: 60s
        port: 9100
      relabel_configs:
      - action: labelmap
        regex: __meta_ec2_tag_(.+)
