apiVersion: v1
kind: Service
metadata:
  labels:
    name: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  type: ClusterIP
  ports:
  - name: alertmanager
    port: 9093
    targetPort: 9093
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.4.2
        ports:
        - containerPort: 9093
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/alertmanager
            name: alertmanager
      volumes:
        - name: alertmanager
          configMap:
            name: alertmanager
            items:
              - key: config.yml
                path: config.yml
