apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-monitoring
  labels:
    prometheus: ambassador
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      ambassador: monitoring
  resources:
    requests:
      memory: 300Mi