apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-ambassador
  labels:
    prometheus: frontend
spec:
  serviceMonitorSelector:
    matchExpressions:
    - {key: ambassador-monitor, operator: Exists}
    - {key: k8s-app, operator: Exists}
    - ambassador: monitoring
    - key: ambassador
      operator: In
      values:
      - "true"

  resources:
    requests:
      memory: 200Mi