apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: ambassador
  name: prometheus-ambassador
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: ambassador