apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  grafana_mapping
      prefix: /
      host: grafana.ddevg.com
      rewrite: "/"
      service: grafana.monitoring:3000
  name: grafana
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: grafana
